"""Alert and Escalation models.

Covers: alerts, alert_escalations, notification_log, notification_subscriptions.
"""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    ForeignKeyConstraint,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from scvri_shared.models.base import (
    Base,
    TimestampMixin,
    TenantMixin,
    UUIDPrimaryKeyMixin,
)

if TYPE_CHECKING:
    pass


AlertStatus = Enum(
    "open",
    "acknowledged",
    "in_progress",
    "resolved",
    "suppressed",
    name="alert_status_enum",
    schema="alerting",
)

AlertSeverity = Enum(
    "critical",
    "high",
    "medium",
    "low",
    "informational",
    name="alert_severity_enum",
    schema="alerting",
)

NotificationChannel = Enum(
    "email",
    "slack",
    "teams",
    "sms",
    "pagerduty",
    "webhook",
    name="notification_channel_enum",
    schema="alerting",
)


class Alert(Base, UUIDPrimaryKeyMixin, TenantMixin, TimestampMixin):
    """Alert record generated by the Alert Engine.

    Citus distribution: tenant_id.
    Partitioned by created_at (quarterly) — handled in migration DDL.
    """

    __tablename__ = "alerts"
    __table_args__ = (
        Index("idx_alert_tenant_status", "tenant_id", "status"),
        Index("idx_alert_supplier", "tenant_id", "supplier_id"),
        Index("idx_alert_severity", "tenant_id", "severity"),
        Index("idx_alert_created", "tenant_id", "created_at"),
        {"schema": "alerting"},
    )

    # ------------------------------------------------------------------ #
    # Source
    # ------------------------------------------------------------------ #
    rule_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    rule_code: Mapped[str | None] = mapped_column(String(50), nullable=True)
    supplier_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    shipment_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    trigger_event_id: Mapped[str | None] = mapped_column(
        String(200), nullable=True
    )  # Kafka message ID
    trigger_event_type: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # ------------------------------------------------------------------ #
    # Content
    # ------------------------------------------------------------------ #
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    severity: Mapped[str] = mapped_column(AlertSeverity, nullable=False)
    status: Mapped[str] = mapped_column(
        AlertStatus, nullable=False, server_default="open"
    )
    recommended_actions: Mapped[list[str] | None] = mapped_column(JSONB, nullable=True)
    context_data: Mapped[dict | None] = mapped_column(
        JSONB, nullable=True
    )  # snapshot of risk data at alert time

    # ------------------------------------------------------------------ #
    # Assignment / acknowledgment
    # ------------------------------------------------------------------ #
    assigned_to: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    acknowledged_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    acknowledged_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    resolved_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolution_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ------------------------------------------------------------------ #
    # Deduplication (Redis NX key pointer)
    # ------------------------------------------------------------------ #
    dedup_key: Mapped[str | None] = mapped_column(
        String(300), nullable=True
    )  # {rule_code}:{supplier_id}:{window_bucket}

    # ------------------------------------------------------------------ #
    # Escalation tracking
    # ------------------------------------------------------------------ #
    escalation_level: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    last_escalated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    escalations: Mapped[list[AlertEscalation]] = relationship(
        "AlertEscalation",
        back_populates="alert",
        lazy="noload",
        cascade="all, delete-orphan",
    )
    notifications: Mapped[list[NotificationLog]] = relationship(
        "NotificationLog",
        back_populates="alert",
        lazy="noload",
    )


class AlertEscalation(Base, UUIDPrimaryKeyMixin, TenantMixin, TimestampMixin):
    """One record per escalation level change on an alert."""

    __tablename__ = "alert_escalations"
    __table_args__ = (
        ForeignKeyConstraint(
            ["alert_id", "tenant_id"],
            ["alerting.alerts.id", "alerting.alerts.tenant_id"],
            name="fk_escalation_alert",
            ondelete="CASCADE",
        ),
        Index("idx_escalation_alert", "tenant_id", "alert_id"),
        {"schema": "alerting"},
    )

    alert_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    from_level: Mapped[int] = mapped_column(Integer, nullable=False)
    to_level: Mapped[int] = mapped_column(Integer, nullable=False)
    escalated_to_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )
    escalated_to_role: Mapped[str | None] = mapped_column(String(100), nullable=True)
    reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    escalated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    alert: Mapped[Alert] = relationship("Alert", back_populates="escalations", lazy="noload")


class NotificationLog(Base, UUIDPrimaryKeyMixin, TenantMixin, TimestampMixin):
    """Delivery record for every notification attempt."""

    __tablename__ = "notification_log"
    __table_args__ = (
        ForeignKeyConstraint(
            ["alert_id", "tenant_id"],
            ["alerting.alerts.id", "alerting.alerts.tenant_id"],
            name="fk_notif_alert",
            ondelete="CASCADE",
        ),
        Index("idx_notif_alert", "tenant_id", "alert_id"),
        Index("idx_notif_status", "tenant_id", "status"),
        {"schema": "alerting"},
    )

    alert_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    channel: Mapped[str] = mapped_column(NotificationChannel, nullable=False)
    recipient: Mapped[str] = mapped_column(
        String(500), nullable=False
    )  # email addr, Slack user ID, etc.
    status: Mapped[str] = mapped_column(
        Enum(
            "pending",
            "sent",
            "delivered",
            "failed",
            "skipped",
            name="notif_status_enum",
            schema="alerting",
        ),
        nullable=False,
        server_default="pending",
    )
    attempt_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    last_attempt_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    next_retry_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    external_message_id: Mapped[str | None] = mapped_column(
        String(500), nullable=True
    )  # SES message ID, Slack ts, etc.
    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    alert: Mapped[Alert] = relationship("Alert", back_populates="notifications", lazy="noload")


class NotificationSubscription(Base, UUIDPrimaryKeyMixin, TenantMixin, TimestampMixin):
    """Tenant-level routing config: which events go to which channels."""

    __tablename__ = "notification_subscriptions"
    __table_args__ = (
        Index("idx_notif_sub_tenant", "tenant_id"),
        {"schema": "alerting"},
    )

    user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )  # NULL = role-level subscription
    role: Mapped[str | None] = mapped_column(String(100), nullable=True)
    channel: Mapped[str] = mapped_column(NotificationChannel, nullable=False)
    destination: Mapped[str] = mapped_column(
        String(1000), nullable=False
    )  # email addr, Slack webhook URL, etc.
    severity_filter: Mapped[list[str] | None] = mapped_column(
        JSONB, nullable=True
    )  # restrict to ["critical","high"] etc.
    rule_filter: Mapped[list[str] | None] = mapped_column(
        JSONB, nullable=True
    )  # restrict to specific rule codes
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")


class WebhookEndpoint(Base, UUIDPrimaryKeyMixin, TenantMixin, TimestampMixin):
    """Third-party webhook subscription (HMAC-SHA256 signed deliveries)."""

    __tablename__ = "webhook_endpoints"
    __table_args__ = (
        UniqueConstraint("tenant_id", "endpoint_url", name="uq_webhook_tenant_url"),
        {"schema": "alerting"},
    )

    endpoint_url: Mapped[str] = mapped_column(String(2000), nullable=False)
    signing_secret_encrypted: Mapped[str] = mapped_column(
        Text, nullable=False
    )  # AES-256 encrypted in KMS; never exposed in API responses
    events_subscribed: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False
    )  # ["risk_score.critical", "alert.created", ...]
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")
    failure_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    last_success_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    last_failure_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
