"""SQLAlchemy ORM base and shared mixins.

All models inherit from ``Base``.  Citus distribution is handled through
raw DDL in Alembic migrations — SQLAlchemy is unaware of it.
"""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, String, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Central declarative base for all SCVRI models."""

    # Provide a default __repr__ useful for debugging
    def __repr__(self) -> str:
        cls = type(self).__name__
        pk_col = next(
            (
                c.key
                for c in type(self).__table__.columns  # type: ignore[attr-defined]
                if c.primary_key
            ),
            "id",
        )
        pk_val = getattr(self, pk_col, "?")
        return f"<{cls} {pk_col}={pk_val!r}>"

    def to_dict(self) -> dict[str, Any]:
        """Shallow conversion to dict (excludes relationships)."""
        return {
            col.key: getattr(self, col.key)
            for col in type(self).__table__.columns  # type: ignore[attr-defined]
        }


# ---------------------------------------------------------------------------
# Mixins
# ---------------------------------------------------------------------------
class TimestampMixin:
    """Adds ``created_at`` and ``updated_at`` columns to any model."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class UUIDPrimaryKeyMixin:
    """UUID v4 primary key generated by the database."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TenantMixin:
    """Multi-tenant isolation column.

    All tenant-scoped tables include this column.  Row-Level Security
    policies reference ``current_setting('scvri.tenant_id')``.
    """

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
    )


class SoftDeleteMixin:
    """Logical delete support — records are never physically removed
    unless a GDPR erasure workflow explicitly purges them.
    """

    is_deleted: Mapped[bool] = mapped_column(default=False, nullable=False)
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
